config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: 'hq/sessions'}, path: 'hq',
             path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret',
                          confirmation: 'verification'}
  devise_for :users
  root to: 'welcome#index'

  resource :user_profile, except: [:destroy], path: 'profile'

  namespace :hq do
      root to: 'dashboard#index'
      resource :admin_profile, except: [:destroy], path: 'profile'
      resources :dashboard, only: [:index]
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
        has_one :admin_profile
        accepts_nested_attributes_for :admin_profile
end

app/models/admin_profile.rb
class AdminProfile < ActiveRecord::Base
  belongs_to :admin
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        has_one :user_profile
        accepts_nested_attributes_for :user_profile
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_user_time_zone
  respond_to :html, :json


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
  # rescue_from Exception, :with => :server_error
  def server_error(exception)
    # ExceptionNotifier::Notifier.exception_notification(request.env, exception).deliver
    respond_to do |format|
      format.html { render template: 'errors/internal_server_error', layout: 'layouts/application', status: 500 }
      format.all  { render nothing: true, status: 500}
    end
  end

  rescue_from ActiveRecord::RecordNotFound, :with => :page_not_found
  rescue_from ActionController::RoutingError, :with => :page_not_found
  def page_not_found
    respond_to do |format|
      format.html { render template: 'errors/not_found', layout: 'layouts/application', status: 404 }
      format.all  { render nothing: true, status: 404 }
    end
  end
protected
  def set_user_time_zone
    Time.zone = current_user.time_zone if user_signed_in? && current_user.time_zone.present?
  end

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super # Use the default one
    end
  end

end

app/controllers/hq/admin_profiles_controller.rb
# encoding: UTF-8
class Hq::AdminProfilesController < Hq::ApplicationController
  
  before_action :check_profile, only: [:new, :create]
  before_action :profile_controller, except: [:new, :create] 
  before_action :set_admin_profile, only: [:show, :edit, :update]
  add_breadcrumb I18n.t('activerecord.models.admin_profiles'), :hq_admin_profile_path

  def show
    add_breadcrumb @admin_profile.first_name, hq_admin_profile_path
    respond_with([:hq, @admin_profile])
  end

  def new
    add_breadcrumb t('tooltips.new'), new_hq_admin_profile_path
    @admin_profile = current_admin.build_admin_profile
    respond_with([:hq, @admin_profile])
  end

  def edit
    add_breadcrumb t('tooltips.edit'), edit_hq_admin_profile_path
  end

  def create
    @admin_profile = current_admin.build_admin_profile(admin_profile_params)
    @admin_profile.save
    respond_with([:hq, @admin_profile], location: hq_admin_profile_path)
  end

  def update
    @admin_profile.update(admin_profile_params)
    respond_with([:hq, @admin_profile], location: hq_admin_profile_path)
  end

  private

  def profile_controller
    if current_admin.admin_profile.nil?
      redirect_to new_hq_admin_profile_path
    end
  end

  def check_profile
    if current_admin.admin_profile.present?
      redirect_to user_profile_path
    end
  end

  def set_admin_profile
    @admin_profile = current_admin.admin_profile
  end

  def admin_profile_params
    params.require(:admin_profile).permit(:first_name, :gsm, :last_name)
  end
end

app/controllers/hq/application_controller.rb
require 'application_responder'

class Hq::ApplicationController < ActionController::Base
  before_action :authenticate_admin!
  self.responder = ApplicationResponder
  respond_to :html, :json
end

app/controllers/hq/dashboard_controller.rb
class Hq::DashboardController < Hq::ApplicationController
  def index

  end
end

app/controllers/hq/sessions_controller.rb
class Hq::SessionsController < Devise::SessionsController
  layout 'login'

  private

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    hq_root_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end
  
end

app/controllers/user_profiles_controller.rb
# encoding: UTF-8
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_profile, only: [:new, :create]
  before_action :profile_controller, except: [:new, :create]
  before_action :set_user_profile, only: [:show, :edit, :update]
  add_breadcrumb I18n.t('activerecord.models.user_profiles'), :user_profile_path

  def show
    add_breadcrumb @user_profile.first_name, user_profile_path
    respond_with(@user_profile)
  end

  def new
    add_breadcrumb t('tooltips.new'), new_user_profile_path
    @user_profile = current_user.build_user_profile
    respond_with(@user_profile)
  end

  def edit
    add_breadcrumb t('tooltips.edit'), edit_user_profile_path
  end

  def create
    @user_profile = current_user.build_user_profile(user_profile_params)
    @user_profile.save
    respond_with(@user_profile, location: user_profile_path)
  end

  def update
    @user_profile.update(user_profile_params)
    respond_with(@user_profile, location: user_profile_path)
  end

  private

  def profile_controller
    if current_user.user_profile.nil?
      redirect_to new_user_profile_path
    end
  end

  def check_profile
    if current_user.user_profile.present?
      redirect_to user_profile_path
    end
  end

  def set_user_profile
    @user_profile = current_user.user_profile
  end

  def user_profile_params
    params.require(:user_profile).permit(:first_name, :gsm, :last_name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hq/admin_profiles/_form.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title
  .panel-body
    = simple_form_for([:hq, @admin_profile], url: hq_admin_profile_path) do |f|
      = f.error_notification

      .form-inputs
        = f.input :first_name
        = f.input :last_name
        = f.input :gsm
      .form-actions
        = f.button :submit, class: 'btn btn-default'
        = link_to t('cancel'), hq_admin_profile_path, class: 'btn'

app/views/hq/admin_profiles/edit.html.haml
- content_for :form_title do
  = t('tt.edit', resource_name: AdminProfile.model_name.human)
= render 'form'

app/views/hq/admin_profiles/new.html.haml
- content_for :form_title do
  = t('tt.new', resource_name: AdminProfile.model_name.human)
= render 'form'

app/views/hq/admin_profiles/show.html.haml
- content_for :toolbar do
  = link_to edit_hq_admin_profile_path, class: 'btn btn-default' do
    %i.icon-pencil
    = t('action_button.edit')
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = t('tt.show', resource_name: AdminProfile.model_name.human)
  .panel-body
    = show_for @admin_profile do |s|
      = s.attribute :first_name
      = s.attribute :last_name
      = s.attribute :gsm

app/views/hq/dashboard/index.html.haml
%h1= "Hi #{current_admin.email}"
= link_to 'Sign out', destroy_admin_session_path, class: 'btn btn-large', method: :delete
= link_to 'Edit Profile', edit_hq_admin_profile_path, class: 'btn btn-large'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title note
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container-narrow
      .masthead
        %ul.nav.nav-pills.pull-right
          %li.active
            %a{:href => "/"} Home
          %li
            %a{:href => "/rails/routes"} Routes
        %h3.muted= link_to "note", root_path
      %hr/
      = render partial: 'layouts/partials/messages'
      = yield
      %hr/
      .footer
        %p © Company 2013

app/views/layouts/hq/application.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114x114-precomposed.png")

    = csrf_meta_tags

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'hq/application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css',
                          media: 'all', 'data-turbolinks-track' => true

    / Javascripts
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                              'hq/application', 'data-turbolinks-track' => true
    = yield :head

  %body.main

    / Navbar
    = render partial: 'layouts/hq/partials/navbar'

    #wrapper

      / Sidebar
      %section#sidebar
        = render partial: 'layouts/hq/partials/dock'

      / Tools
      %section#tools
        = render partial: 'layouts/hq/partials/breadcrumb'
        = render partial: 'layouts/hq/partials/toolbar'

      / Content
      #content
        = render partial: 'layouts/partials/messages'
        = yield

    / Footer
    = render partial: 'layouts/hq/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/hq/partials/_breadcrumb.haml
%ul#breadcrumb.breadcrumb
  = render_breadcrumbs :separator => ' / '

app/views/layouts/hq/partials/_dock.haml
%i#toggle.icon-align-justify.icon-large

%ul#dock
  %li.launcher
    %i.icon-dashboard
    =link_to  t('dock.dashboard'), hq_dashboard_index_path
  %li.launcher
    %i.icon-file-text-alt
    =link_to 'Forms', '/hq/dashboard/form.html'
  %li.launcher
    %i.icon-table
    =link_to 'Tables', '/hq/dashboard/tables.html'
  %li.launcher.dropdown.hover
    %i.icon-flag
    %a{href: '#'} Reports
    %ul.dropdown-menu
      %li.dropdown-header Launcher description
      %li
        %a{:href => '#'} Action
      %li
        %a{:href => '#'} Another action
      %li
        %a{:href => '#'} Something else here
  %li.launcher
    %i.icon-bookmark
    %a{href: '#'} Bookmarks
  %li.launcher
    %i.icon-cloud
    %a{href: '#'} Backup
  %li.launcher
    %i.icon-bug
    %a{href: '#'} Feedback

#beaker{data: {toggle: 'tooltip'}, title: 'Made by lab2023'}

app/views/layouts/hq/partials/_footer.haml
= yield :foot

app/views/layouts/hq/partials/_navbar.haml
#navbar.navbar.navbar-default
  %a.navbar-brand{:href => hq_root_path}
    %i.icon-beer
    Hierapolis
  %ul.nav.navbar-nav.pull-right
    %li.dropdown
      %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
        %i.icon-envelope
        Messages
        %span.badge 5
        %b.caret
      %ul.dropdown-menu
        %li
          %a{:href => '#'} New message
        %li
          %a{:href => '#'} Inbox
        %li
          %a{:href => '#'} Out box
        %li
          %a{:href => '#'} Trash
    %li
      %a{href: '#'}
        %i.icon-cog
        = t('navbar.settings')
    %li.dropdown.user
      %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
        %i.icon-user
        %strong
          = current_admin.email
        =image_tag 'http://lorempixel.com/output/fashion-q-c-20-20-4.jpg', width: '20px', height: '20px', class: 'img-rounded'
        %b.caret
      %ul.dropdown-menu
        %li
          =link_to t('navbar.edit_profile'), edit_hq_admin_profile_path
        %li.divider
        %li
          =link_to t('navbar.signout'), destroy_admin_session_path, method: :delete

app/views/layouts/hq/partials/_toolbar.haml
#toolbar
  .btn-group
    = yield :toolbar

app/views/layouts/login.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114x114-precomposed.png")

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'hq/application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css',
                          media: 'all', 'data-turbolinks-track' => true
    = yield :head

  %body.login

    .wrapper
      = render partial: 'layouts/partials/messages'
      = yield

    / Footer
    = render partial: 'layouts/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/partials/_footer.haml
/ Javascripts
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                         'application', 'data-turbolinks-track' => true

app/views/layouts/partials/_messages.haml
- flash.each do |key, value|
  - if key.to_s == "notice"
    - key = "success"
  - if key.to_s == "alert"
    - key = "danger"
  %div{:class => "alert alert-dismissable alert-#{key}"}
    - if key.to_s == "danger" || key.to_s == "warning"
      %i.fa.fa-exclamation-triangle.fs-25
      %strong
        = t('messages.sorry')
        \!
    - else
      %i.fa.fa-smile-o.fs-25{:style => "padding: 0px 5px;"}
    = value

app/views/layouts/partials/_trackers.haml
:javascript
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/user_profiles/_form.html.haml
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = yield :form_title
  .panel-body
    = simple_form_for(@user_profile, url: user_profile_path) do |f|
      = f.error_notification

      .form-inputs
        = f.input :first_name
        = f.input :last_name
        = f.input :gsm

      .form-actions
        = f.button :submit, class: 'btn btn-default'
        = link_to t('cancel'), user_profile_path, class: 'btn'

app/views/user_profiles/edit.html.haml
- content_for :form_title do
  = t('tt.edit', resource_name: UserProfile.model_name.human)
= render 'form'

app/views/user_profiles/new.html.haml
- content_for :form_title do
  = t('tt.new', resource_name: UserProfile.model_name.human)
= render 'form'

app/views/user_profiles/show.html.haml
- content_for :toolbar do
  = link_to edit_user_profile_path, class: 'btn btn-default' do
    %i.icon-pencil
    = t('action_button.edit')
.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    = t('tt.show', resource_name: UserProfile.model_name.human)
  .panel-body
    = show_for @user_profile do |s|
      = s.attribute :first_name
      = s.attribute :last_name
      = s.attribute :gsm

app/views/welcome/index.html.haml
.jumbotron
  %h1 Welcome to note
  - if current_user
    = link_to 'Sign out', destroy_user_session_path, class: 'btn btn-large', method: :delete
    .row-fluid.marketing
      %p
        %strong Name:
        = current_user.name
      %p
        %strong Email:
        = current_user.email
    = link_to 'Edit Profile', edit_user_profile_path, class: 'btn btn-large'
  - else
    = link_to 'Sign up today', new_user_registration_path, class: 'btn btn-large btn-success'
    = link_to 'Sign in', new_user_session_path, class: 'btn btn-large'